### PR TITLE
SE-1356 Modify features endpoint to dynamically set requested features.

### PR DESCRIPTION
**Pull request by medhatphq**
* Modify features endpoint schema to dynamically set requested features so we don't have to explicitly update the schema when new features are implemented.

### CODE REVIEW

**Review by CockyAmoeba — APPROVED** [review]
Noice 👍

**Review by lpouvreau — APPROVED** [review]
Nicely done, thanks @medhatphq  🙂

**Comment by hhheath** [comment]
hey @medhatphq things seem to be working better now, but I am now getting _all_ stats instead of just the ones requested. 
image
image

**Comment by medhatphq** [comment]
> hey @medhatphq things seem to be working better now, but I am now getting _all_ stats instead of just the ones requested. 

Discusssed with @hhheath and we agreed the right solution to hiding None values is to use `.model_dump(exclude_none=True)` when serialising feature data.

The other solution is to explicitly access the requested fields only, as documented in the README and usecases.

We also agreed that I will add notes in the README and usecases to document the usage of `model_dump(exclude_none=True)`

**Pull request merged**
